### ISSUE TITLE
Output values for keys directly

### ISSUE THREAD

**Issue by Apocryphon** [dominictarr/JSON.sh#12]
What is the best way to output the corresponding value for any line of the output of this script, given a key?

**Comment by Tomaskom-cz** [comment]
(copying from another issue thread where I posted this)
I use the following two functions for extracting values from the JSON.sh output: 
```
#function to get value of specified key
#returns empty string if not found
#warning - does not validate key format (supplied as parameter) in any way, simply returns empty string for malformed queries too
#usage: VAR=$(getkey foo.bar) #get value of "bar" contained within "foo"
#       VAR=$(getkey foo[4].bar) #get value of "bar" contained in the array "foo" on position 4
#       VAR=$(getkey [4].foo) #get value of "foo" contained in the root unnamed array on position 4
function getkey {
    #reformat key string (parameter) to what JSON.sh uses
    KEYSTRING=$(sed -e 's/\[/\"\,/g' -e 's/^\"\,/\[/g' -e 's/\]\./\,\"/g' -e 's/\./\"\,\"/g' -e '/^\[/! s/^/\[\"/g' -e '/\]$/! s/$/\"\]/g' <<< "$@")
    #extract the key value
    FOUT=$(grep -F "$KEYSTRING" <<< "$JSON_PARSED")
    FOUT="${FOUT#*$'\t'}"
    FOUT="${FOUT#*\"}"
    FOUT="${FOUT%\"*}"
    echo "$FOUT"
}

#function returning length of array
#returns zero if key in parameter does not exist or is not an array
#usage: VAR=$(getarrlen foo.bar) #get length of array "bar" contained within "foo"
#       VAR=$(getarrlen) #get length of the root unnamed array
#       VAR=$(getarrlen [2].foo.bar) #get length of array "bar" contained within "foo", which is stored in the root unnamed array on position 2
function getarrlen {
    #reformat key string (parameter) to what JSON.sh uses
    KEYSTRING=$(sed -e '/^\[/! s/\[/\"\,/g' -e 's/\]\./\,\"/g' -e 's/\./\"\,\"/g' -e '/^$/! {/^\[/! s/^/\[\"/g}' -e '/^$/! s/$/\"\,/g' -e 's/\[/\\\[/g' -e 's/\]/\\\]/g' -e 's/\,/\\\,/g' -e '/^$/ s/^/\\\[/g' <<< "$@")
    #extract the key array length - get last index
    LEN=$(grep -o "${KEYSTRING}[0-9]*" <<< "$JSON_PARSED" | tail -n -1 | grep -o "[0-9]*$")
    #increment to get length, if empty => zero
    if [ -n "$LEN" ]; then
        LEN=$(($LEN+1))
    else
        LEN="0"
    fi
    echo "$LEN"
}
```
It expects the JSON.sh to be run with the `-l` flag and output stored in the variable `$JSON_PARSED`.

What does it do? I take the key in the simple form `foo.bar[i].var` and convert them to the `JSON.sh` output format via sed. Those are then used for grepping out the value (yeah, the final extraction could be a bit smarter), or obtaining the length of an array.

**Comment by decibel** [comment]
Interesting... why not pass in the parsed JSON instead of forcing a 
particular variable? It'd probably be useful to add these to JSON.sh so 
they're available if you've sourced the script.

**Comment by Tomaskom-cz** [comment]
Using `$JSON_PARSED` as source for the data is a cosmetic detail, I copied it directly from my own script (where I work with the same parsed JSON the whole time). 
The JSON could be of course passed as a second parameter - all you need to do is replace `$@` with `$1` and `$JSON_PARSED` with `$2`, then use it like `VAR=$(getkey foo.bar "$JSON_PARSED")`.

**Comment by decibel** [comment]
Sounds good; I'll take a stab at adding these functions.
